### ISSUE TITLE
Spel loopt soms vast na roteren wereld

### ISSUE THREAD

**Issue by wietseneven** [wietseneven/VR-Hackastory-Breda#1]

**Comment by hansvana** [comment]
Wat bedoel je met vastlopen? Dat de innerView niet meer een bepaalde richting op wil, maar dat je nog wel kan draaien enzo?

**Comment by wietseneven** [comment]
Jup, precies dat

**Comment by frenkie** [comment]
Ook nog even besproken met Michiel, kwam het ook tegen. Was waarschijnlijk wanneer je roteerde terwijl iemand nog aan t lopen is. Zo ja, dan of t lopen afbreken of zorgen dat er niet gedraaid kan worden tojdens het verplaatsen

**Comment by hansvana** [comment]
setRotateTo() kan nu alleen gestart worden als isBusy() false returnt, hopelijk lost dat het op.
