### ISSUE TITLE
mogelijk maken dat er parallel ontwikkeld kan worden

### ISSUE THREAD

**Issue by frenkie** [wietseneven/VR-Hackastory-Breda#2]
We hebben nu allemaal een eigen stukje ontwikkeld en soort van samengevoegd, maar eigenlijk ook nog weer niet. Lijkt mij gaaf om de code architectuur zo op te zetten dat er ies makkelijker met meerdere ontwikkelaars aan gewerkt kan worden in een programmeerstijl die niet te dwingend is in 1 iemands eigen stijl.

**Comment by hansvana** [comment]
Ik ben nu innerView aan het ombouwen naar iets meer OOP, en heb dingen zoals de map array en de textures naar de global map verplaatst.

**Comment by hansvana** [comment]
Ik denk ook dat we even duidelijk moeten uitspreken wat onze goals zijn. Maken we dit bugvrij en is het dan klaar? Gaan we voor een prototype die ergens openbaar kan komen staan? Gaan we de designers er weer in betrekken en verder ontwikkelen?

Ik wil in ieder geval nog een beter systeem voor de map. Het blokkendoossysteem dat ik nu heb gebruikt is ontzettend complex en onmogelijk te beheren. Meerdere levels zou ook nog een mooie stap zijn.

**Comment by frenkie** [comment]
Heb het er ook nog met Michiel over gehad en we zijn beiden in ieder geval heel erg enthousiast om het in eerste instantie een openbaar prototype te maken dat door meerdere mensen kan worden gespeeld. Wellicht met de buitenwereld voorlopig als desktop in fase 1 en uiteindelijk misschien wel de keuze tussen desktop of VR. Mijn collega Nikki die mee heeft gewerkt aan het verhaal is ook enthousiast en volgens mij krijgen we de designers ook wel mee. Het is dan inderdaad belangrijk om een aantal doelen duidelijk op een rijtje te hebben en ergens af te kunnen strepen (als issues hier in Github wellicht). Bugvrij, online met werkend intro en outro.

Wat betreft code en architectuur. Op dit moment wordt de inner view gerund vanuit /simple-server, als soort van gekopieerde maar ook al n beetje geOOPde code, dus aanpassingen in de /server/examples folder gaan niet mee. Graag wil ik dat veranderen, ook om die code überhaupt wat te refactoren. Ik wil wel jouw OOP als basis gebruiken voor de opzet en een voorstel doen in een andere hoofdfolder.

Het liefst zou ik een front end module laad systeem erin willen gebruiken ipv alle losse scripts inladen in een index.html en met globale variabelen werken. Op die manier kun je goed los aan modules werken, duidelijk aangeven welke dependencies ze hebben, etc. Ik weet alleen niet of jullie a) dat werkbaar vinden en b) of jullie er al ervaring mee hebben / een voorkeur hebben. Ik denk aan bv RequireJS, SystemJS ( ES6 import statements, een polyfill ). Ik begin wel even zonder. @micros123  en @wietseneven jullie nog een mening hierover?

**Comment by frenkie** [comment]
ik maak wel even een git branch, makkelijker

**Comment by frenkie** [comment]
De branch ( https://github.com/wietseneven/VR-Hackastory-Breda/tree/collaboration-setup ) is nu zo opgedeeld dat in de losse foldertjes (innerview, outerview) een index.html kan staan om standalone die view te testen. Daardoor mag de view zichzelf niet initialiseren, dat moet dan gebeuren in de betreffende index.html. Van buiten het foldertje kunnen nu de juiste classes worden geladen en geïnstantieerd wanneer nodig. Zo kan er los getest worden en in-game met player keuze en introotjes vooraf.

**Comment by hansvana** [comment]
Ik heb een grote update voor innerView gepushed naar de master en een wikipagina aangemaakt voor de status van innerView.

**Comment by frenkie** [comment]
@hansvana Ik heb je grote update die nu online op Github staat in de branch 'collaboration-setup' geplaatst. Het enige dat niet gecommit is zijn volgens mij de skyview textures.

Ik heb een paar classes ietwat hernoemd, lees geprefixed met Inner, zodat @micros123 nu in jouw OOP stijl ook de Outerview gaat ombouwen maar dan waar nodig met de Outer prefix in classes. Daarnaast initaliseer ik dus de InnerGame in de index.html.

Kan jij vanaf nu werken in die collaboration branch? Michiel verbouwt de outer view nu, ik het gedeelte met keuze en intro's en ik knoop jullie classes aan elkaar, zodat ik niet jullie code ergens hoef te dupliceren, wat nu gebeurt in de master.  Dan gaan we als daar een werkend prototype staat, die code mergen naar de master en dan wordt dat vanaf dan de master.

Jullie kunnen los jullie wereld testen en de root index.html onder /game/ knoopt alles aan elkaar.

**Comment by frenkie** [comment]
Oh ja, een aantal zaken die jullie beiden zouden kunnen gebruiken heb ik verplaatst naar de global map, zoals de DesktopControls class. Wellicht is er meer dat daar heen kan.

**Comment by hansvana** [comment]
Gaan we iets van commonjs of requirejs gebruiken, of gaan we gewoon gelijk voor es6 modules?

**Comment by frenkie** [comment]
ES6 modules is wel het mooist. Ben nu net bij de VPRO RequireJS aan het vervangen door SystemJS ( https://github.com/systemjs/systemjs ), wel gecharmeerd van. Grotendeels een polyfill voor de ES6 module lader standaard die eraan komt. Voor het gebruik van nog niet ES6 modules zoals de Three.js globals, zie https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md  Vergelijkbaar met shim config van RequireJS    Laat maar weten of je dat wat vindt!

**Comment by frenkie** [comment]
Ik wil er dan wel een opzetje voor maken in onze collab branch

**Comment by frenkie** [comment]
Ik heb nu een tag gemaakt van versie 1.0.0 https://github.com/wietseneven/VR-Hackastory-Breda/tree/v1.0.0  met de oude werkende versie erin. En ik heb net alle code gecommit om de collaboration branch werkend te krijgen vanaf de server root. Die ga ik zo mergen naar de master en forken op de Hackastory Github repository.

**Comment by frenkie** [comment]
De Collaboration branch is gemerged met de master en vanaf nu kan er gewerkt worden op https://github.com/hackastory/dilemma
